spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/easypeacyrecipes?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      location: uploads/
  messages:
    basename: i18n/messages
    encoding: UTF-8
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    org:
      springframework: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8080


jwt:
  secret: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION:60000}

comments:
  api:
    baseUrl: "http://localhost:8081"
